[package]
name = "condemus"
version = "0.1.0"
edition = "2021"

[dependencies]
creak = "0.3.0"
eframe = "0.22.0"
env_logger = "0.10.0"
id-arena = "2.2.1"
serde = { version = "1.0.188", features = ["derive"] }
zip = "0.6.6"
